version: "3.3"
services:
  lunchbot_api:
    build: .
    depends_on:
     - mongodb
    environment: 
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    ports:
      - "3000:3000"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
      - "28017:28017"

  mongo_provision:
    build: ./provision
    depends_on:
     - mongodb